# Generated by Django 4.2.1 on 2024-02-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_instructor_workoutplan_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
    ]
