# Generated by Django 4.2.1 on 2024-02-13 06:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesReport',
            fields=[
                ('expense_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('supplies', 'Supplies'), ('others', 'Others')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_paid', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfitReport',
            fields=[
                ('profit_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryReport',
            fields=[
                ('salary_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_paid', models.DateField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='FeeReport',
            fields=[
                ('fee_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_paid', models.DateField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
    ]
