# Generated by Django 4.2.1 on 2024-02-13 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_expensesreport_profitreport_salaryreport_feereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitreport',
            name='profit',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
