# Generated by Django 4.2.1 on 2024-02-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_profitreport_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=150, unique=True),
        ),
    ]
