# Generated by Django 4.2.1 on 2024-02-13 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customer_email_instructor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialInstruction',
            fields=[
                ('instruction_id', models.AutoField(primary_key=True, serialize=False)),
                ('instruction_text', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
    ]
