# Generated by Django 4.2.1 on 2024-02-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_specialinstruction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialInstruction',
        ),
    ]
