# Generated by Django 4.2.1 on 2024-02-14 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_specialinstruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('body_fat_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('muscle_mass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cardiovascular_endurance', models.PositiveIntegerField()),
                ('strength', models.PositiveIntegerField()),
                ('flexibility', models.PositiveIntegerField()),
                ('other_metrics', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instructor')),
            ],
        ),
    ]
